"""modificacion curso

Revision ID: 046064247d69
Revises: 178c96f70c85
Create Date: 2025-07-10 18:09:11.386248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046064247d69'
down_revision: Union[str, None] = '178c96f70c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('carrera', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'carrera')
    # ### end Alembic commands ###
