"""se modifico disponibilidad

Revision ID: 04d3fa28a0b5
Revises: 5cc48202e023
Create Date: 2025-08-27 10:00:28.879923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '04d3fa28a0b5'
down_revision: Union[str, None] = '5cc48202e023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disponibilidad_docente', sa.Column('horarios', sa.JSON(), nullable=False))
    op.drop_column('disponibilidad_docente', 'hora_inicio')
    op.drop_column('disponibilidad_docente', 'hora_fin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disponibilidad_docente', sa.Column('hora_fin', mssql.TIME(), autoincrement=False, nullable=False))
    op.add_column('disponibilidad_docente', sa.Column('hora_inicio', mssql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('disponibilidad_docente', 'horarios')
    # ### end Alembic commands ###
