"""se creo a asginaciondocentecurso el campo seccion nuleable

Revision ID: 0f95d0d5b29c
Revises: 6a274c91a991
Create Date: 2025-08-22 10:38:14.974214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f95d0d5b29c'
down_revision: Union[str, None] = '6a274c91a991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asignacion_curso_docente', 'seccion',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asignacion_curso_docente', 'seccion',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
