"""modificacion docente no curso

Revision ID: 178c96f70c85
Revises: f72edd4fe4dd
Create Date: 2025-07-10 18:07:52.427485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178c96f70c85'
down_revision: Union[str, None] = 'f72edd4fe4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('horas', sa.Integer(), nullable=True))
    op.drop_column('cursos', 'docente')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('docente', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('cursos', 'horas')
    # ### end Alembic commands ###
