"""Creacion de las relaciones

Revision ID: 1b5ae6dfd77b
Revises: 85035f41f946
Create Date: 2025-08-20 18:29:15.093631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5ae6dfd77b'
down_revision: Union[str, None] = '85035f41f946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
