"""se modifico el character de 

Revision ID: 26de94a5717c
Revises: d4cf42aab129
Create Date: 2025-08-15 17:16:56.883764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26de94a5717c'
down_revision: Union[str, None] = 'd4cf42aab129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cursos', 'nombre',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cursos', 'nombre',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
