"""se modifico tabla asigancion y tabla asignacioncursodocente

Revision ID: 2fe2234799a2
Revises: 4c49ccac6692
Create Date: 2025-08-25 09:25:31.828197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe2234799a2'
down_revision: Union[str, None] = '4c49ccac6692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignacion_curso_docente', sa.Column('es_bloque', sa.Boolean(), nullable=True))
    op.add_column('asignacion_curso_docente', sa.Column('bloque', sa.String(length=1), nullable=True))
    op.add_column('asignacion_curso_docente', sa.Column('duplica_horas', sa.Boolean(), nullable=True))
    op.add_column('asignacion_curso_docente', sa.Column('comentario', sa.Text(), nullable=True))
    op.add_column('asignacion_curso_docente', sa.Column('disponibilidad', sa.String(length=50), nullable=True))
    op.add_column('asignaciones', sa.Column('seccione_asignada', sa.Boolean(), nullable=True))
    op.add_column('asignaciones', sa.Column('nombreseccion', sa.String(length=10), nullable=True))
    op.drop_column('asignaciones', 'secciones_asignadas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones', sa.Column('secciones_asignadas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('asignaciones', 'nombreseccion')
    op.drop_column('asignaciones', 'seccione_asignada')
    op.drop_column('asignacion_curso_docente', 'disponibilidad')
    op.drop_column('asignacion_curso_docente', 'comentario')
    op.drop_column('asignacion_curso_docente', 'duplica_horas')
    op.drop_column('asignacion_curso_docente', 'bloque')
    op.drop_column('asignacion_curso_docente', 'es_bloque')
    # ### end Alembic commands ###
