"""agrega asignacion

Revision ID: 3b0e1b5b6ecb
Revises: 820273440650
Create Date: 2025-07-16 13:21:14.069740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '3b0e1b5b6ecb'
down_revision: Union[str, None] = '820273440650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docenteid', sa.Integer(), nullable=False),
    sa.Column('cursoid', sa.Integer(), nullable=False),
    sa.Column('carreraid', sa.Integer(), nullable=False),
    sa.Column('ciclo', sa.String(length=10), nullable=False),
    sa.Column('cantidad_secciones', sa.Integer(), nullable=False),
    sa.Column('secciones_asignadas', sa.Integer(), nullable=False),
    sa.Column('horas_curso', sa.Integer(), nullable=False),
    sa.Column('horas_actuales', sa.Integer(), nullable=False),
    sa.Column('horas_dejara', sa.Integer(), nullable=True),
    sa.Column('horas_totales', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('fecha_modificada', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['carreraid'], ['carrera.id'], ),
    sa.ForeignKeyConstraint(['cursoid'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['docenteid'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignacion_id'), 'asignacion', ['id'], unique=False)
    op.drop_table('sysdiagrams')
    op.drop_column('cursos', 'horas')
    op.add_column('horarios', sa.Column('horas', sa.Integer(), nullable=True))
    op.drop_column('horarios', 'grupo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horarios', sa.Column('grupo', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('horarios', 'horas')
    op.add_column('cursos', sa.Column('horas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61587074CD')
    )
    op.drop_index(op.f('ix_asignacion_id'), table_name='asignacion')
    op.drop_table('asignacion')
    # ### end Alembic commands ###
