"""actualizo modelo docente creado

Revision ID: 3bc022fc48c7
Revises: 90cbc2ffcee7
Create Date: 2025-07-09 11:42:31.727453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc022fc48c7'
down_revision: Union[str, None] = '90cbc2ffcee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horarios', 'docente')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horarios', sa.Column('docente', sa.VARCHAR(length=100, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
