"""Add horas to Curso

Revision ID: 3d91eec34b97
Revises: f05da398bb8f
Create Date: 2025-07-22 18:01:20.102189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d91eec34b97'
down_revision: Union[str, None] = 'f05da398bb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('horas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'horas')
    # ### end Alembic commands ###
