"""se elimino activo a asignacion

Revision ID: 462874dd55f1
Revises: b93cacf2756b
Create Date: 2025-10-28 10:36:08.764609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '462874dd55f1'
down_revision: Union[str, None] = 'b93cacf2756b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asignaciones', 'activo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones', sa.Column('activo', mssql.BIT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
