"""Cambio a estado no nulleable ta tabla docente

Revision ID: 46420988d340
Revises: fbc8e6d5a2a7
Create Date: 2025-10-23 16:58:12.406618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46420988d340'
down_revision: Union[str, None] = 'fbc8e6d5a2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('docentes', 'correo',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('docentes', 'correo',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
