"""se creo a asginaciondocentecurso el campo seccion

Revision ID: 484e9d8c793e
Revises: 1b5ae6dfd77b
Create Date: 2025-08-22 10:20:41.526720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484e9d8c793e'
down_revision: Union[str, None] = '1b5ae6dfd77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
