"""ahora que no sea nuleable

Revision ID: 4c49ccac6692
Revises: 0f95d0d5b29c
Create Date: 2025-08-22 11:21:59.113090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c49ccac6692'
down_revision: Union[str, None] = '0f95d0d5b29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
