"""creacion de disponibilidad para docent

Revision ID: 4cf4631e1957
Revises: 6503b8d737ca
Create Date: 2025-08-25 13:12:53.531949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf4631e1957'
down_revision: Union[str, None] = '6503b8d737ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disponibilidad_docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disponibilidad_docente_id'), 'disponibilidad_docente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disponibilidad_docente_id'), table_name='disponibilidad_docente')
    op.drop_table('disponibilidad_docente')
    # ### end Alembic commands ###
