"""SE AGREGO TURNO A DISPONIBILIDAD

Revision ID: 5cc48202e023
Revises: 81836482a1e4
Create Date: 2025-08-26 15:55:23.917165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc48202e023'
down_revision: Union[str, None] = '81836482a1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disponibilidad_docente', sa.Column('turno', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disponibilidad_docente', 'turno')
    # ### end Alembic commands ###
