"""Inicial migration

Revision ID: 5de5684db8f4
Revises: 
Create Date: 2025-11-06 12:53:18.500689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de5684db8f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carreraid', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=10), nullable=False),
    sa.Column('ciclo', sa.String(length=10), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad_secciones', sa.Integer(), nullable=True),
    sa.Column('seccion_asignada', sa.Boolean(), nullable=True),
    sa.Column('nombreseccion', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificada', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_id'), 'asignaciones', ['id'], unique=False)
    op.create_table('carrera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('nomenglatura', sa.String(length=1), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomenglatura')
    )
    op.create_index(op.f('ix_carrera_id'), 'carrera', ['id'], unique=False)
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('correo', sa.String(length=50), nullable=False),
    sa.Column('tipocontrato', sa.String(length=50), nullable=False),
    sa.Column('horassemanal', sa.Integer(), nullable=False),
    sa.Column('horasactual', sa.Integer(), nullable=True),
    sa.Column('horastemporales', sa.Integer(), nullable=True),
    sa.Column('horastotales', sa.Integer(), nullable=True),
    sa.Column('horasdejara', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_docentes_id'), 'docentes', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('tipoambiente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('colorhex', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiposevento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ambientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipoid', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('equipamiento', sa.String(length=255), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tipoid'], ['tipoambiente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('modalidad', sa.String(length=30), nullable=True),
    sa.Column('nombre', sa.String(length=500), nullable=True),
    sa.Column('horas', sa.Integer(), nullable=True),
    sa.Column('ciclo', sa.String(length=50), nullable=True),
    sa.Column('plan', sa.String(length=10), nullable=True),
    sa.Column('carreid', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('horasasignadas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carreid'], ['carrera.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('disponibilidad_docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('horarios', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disponibilidad_docente_id'), 'disponibilidad_docente', ['id'], unique=False)
    op.create_table('seccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=True),
    sa.Column('carreraid', sa.Integer(), nullable=True),
    sa.Column('ciclo', sa.Integer(), nullable=True),
    sa.Column('letra', sa.String(length=1), nullable=True),
    sa.Column('turno', sa.String(length=1), nullable=True),
    sa.Column('serie', sa.Integer(), nullable=True),
    sa.Column('modalidad', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['carreraid'], ['carrera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seccion_id'), 'seccion', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('email_verificado', sa.Boolean(), nullable=True),
    sa.Column('rolid', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fechacreacion', sa.DateTime(), nullable=True),
    sa.Column('fechaactualizacion', sa.DateTime(), nullable=True),
    sa.Column('calle_tipo', sa.String(length=20), nullable=True),
    sa.Column('calle_nombre', sa.String(length=100), nullable=True),
    sa.Column('calle_numero', sa.String(length=10), nullable=True),
    sa.Column('ciudad', sa.String(length=50), nullable=True),
    sa.Column('departamento', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=50), nullable=True),
    sa.Column('contacto_numero', sa.String(length=20), nullable=True),
    sa.Column('correo_alternativo', sa.String(length=100), nullable=True),
    sa.Column('cod_docente', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['rolid'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('asignacion_curso_docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('seccion', sa.Integer(), nullable=True),
    sa.Column('es_bloque', sa.Boolean(), nullable=True),
    sa.Column('bloque', sa.String(length=1), nullable=True),
    sa.Column('duplica_horas', sa.Boolean(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('disponibilidad', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignacion_curso_docente_id'), 'asignacion_curso_docente', ['id'], unique=False)
    op.create_table('asignacion_seccion',
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], ),
    sa.PrimaryKeyConstraint('asignacion_id', 'seccion_id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambienteid', sa.Integer(), nullable=True),
    sa.Column('cursoid', sa.Integer(), nullable=True),
    sa.Column('horas', sa.Integer(), nullable=True),
    sa.Column('diasemana', sa.String(length=15), nullable=True),
    sa.Column('horainicio', sa.String(length=5), nullable=True),
    sa.Column('horafin', sa.String(length=5), nullable=True),
    sa.Column('docenteid', sa.Integer(), nullable=True),
    sa.Column('seccionid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ambienteid'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['cursoid'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['docenteid'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['seccionid'], ['seccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('aprobador_id', sa.Integer(), nullable=True),
    sa.Column('ambiente_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('hora_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADA', 'RECHAZADA', name='estadoreserva'), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_evento_id'], ['tiposevento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aprobaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservaid', sa.Integer(), nullable=True),
    sa.Column('aprobadorid', sa.Integer(), nullable=True),
    sa.Column('tipoaprobador', sa.Enum('DOCENTE', 'COORDINADOR', 'SOPORTETI', 'PROGRAMACION', 'ADMINISTRADOR', 'INVITADO', name='rolusuario'), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaprobacion'), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['aprobadorid'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reservaid'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacorareservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=True),
    sa.Column('realizadopor', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventosespeciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservaid', sa.Integer(), nullable=True),
    sa.Column('nombreevento', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('horainicio', sa.String(length=5), nullable=True),
    sa.Column('horafin', sa.String(length=5), nullable=True),
    sa.Column('organizador', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['reservaid'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventosespeciales')
    op.drop_table('bitacorareservas')
    op.drop_table('aprobaciones')
    op.drop_table('reservas')
    op.drop_table('horarios')
    op.drop_table('asignacion_seccion')
    op.drop_index(op.f('ix_asignacion_curso_docente_id'), table_name='asignacion_curso_docente')
    op.drop_table('asignacion_curso_docente')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_seccion_id'), table_name='seccion')
    op.drop_table('seccion')
    op.drop_index(op.f('ix_disponibilidad_docente_id'), table_name='disponibilidad_docente')
    op.drop_table('disponibilidad_docente')
    op.drop_table('cursos')
    op.drop_table('ambientes')
    op.drop_table('tiposevento')
    op.drop_table('tipoambiente')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_docentes_id'), table_name='docentes')
    op.drop_table('docentes')
    op.drop_index(op.f('ix_carrera_id'), table_name='carrera')
    op.drop_table('carrera')
    op.drop_index(op.f('ix_asignaciones_id'), table_name='asignaciones')
    op.drop_table('asignaciones')
    # ### end Alembic commands ###
