"""creacion tabla carrera

Revision ID: 5efcdf0aec8c
Revises: 046064247d69
Create Date: 2025-07-10 18:26:01.431518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efcdf0aec8c'
down_revision: Union[str, None] = '046064247d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('nomenglatura', sa.String(length=1), nullable=True),
    sa.Column('turno', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrera_id'), 'carrera', ['id'], unique=False)
    op.add_column('cursos', sa.Column('carreraid', sa.Integer(), nullable=True))
    op.add_column('cursos', sa.Column('ciclo', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'cursos', 'carrera', ['carreraid'], ['id'])
    op.drop_column('cursos', 'carrera')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('carrera', sa.VARCHAR(length=70, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cursos', type_='foreignkey')
    op.drop_column('cursos', 'ciclo')
    op.drop_column('cursos', 'carreraid')
    op.drop_index(op.f('ix_carrera_id'), table_name='carrera')
    op.drop_table('carrera')
    # ### end Alembic commands ###
