"""creacion de modalidad

Revision ID: 6123d788e8f2
Revises: d03e870f9664
Create Date: 2025-08-07 12:45:14.472779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6123d788e8f2'
down_revision: Union[str, None] = 'd03e870f9664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones', sa.Column('modalidad', sa.String(length=20), nullable=True))
    op.add_column('seccion', sa.Column('modalidad', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seccion', 'modalidad')
    op.drop_column('asignaciones', 'modalidad')
    # ### end Alembic commands ###
