"""se hizo creo activo a labla asignacioncursodocente

Revision ID: 6503b8d737ca
Revises: e0e5c1c0c47c
Create Date: 2025-08-25 09:49:22.917389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6503b8d737ca'
down_revision: Union[str, None] = 'e0e5c1c0c47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignacion_curso_docente', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asignacion_curso_docente', 'activo')
    # ### end Alembic commands ###
