"""Agregar campos de contacto a usuarios

Revision ID: 668b77d003d0
Revises: 9c4d31175c72
Create Date: 2025-08-28 15:30:02.293809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668b77d003d0'
down_revision: Union[str, None] = '9c4d31175c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('telefono', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('contacto_emergencia', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('correo_alternativo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'correo_alternativo')
    op.drop_column('usuarios', 'contacto_emergencia')
    op.drop_column('usuarios', 'telefono')
    op.drop_column('usuarios', 'direccion')
    # ### end Alembic commands ###
