"""agrega estado a la tabla curso

Revision ID: 676d1c9d82c9
Revises: dd540581b3d0
Create Date: 2025-07-22 17:09:52.660109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676d1c9d82c9'
down_revision: Union[str, None] = 'dd540581b3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('estado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'estado')
    # ### end Alembic commands ###
