"""agregar fecha a las secciones y estado docente

Revision ID: 6809e202ad19
Revises: c690cf78c0a5
Create Date: 2025-07-15 18:15:38.271877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '6809e202ad19'
down_revision: Union[str, None] = 'c690cf78c0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.add_column('seccion', sa.Column('fecha_creacion', sa.Date(), nullable=True))
    op.add_column('seccion', sa.Column('fecha_inicio', sa.Date(), nullable=True))
    op.add_column('seccion', sa.Column('fecha_fin', sa.Date(), nullable=True))
    op.add_column('seccion', sa.Column('estado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seccion', 'estado')
    op.drop_column('seccion', 'fecha_fin')
    op.drop_column('seccion', 'fecha_inicio')
    op.drop_column('seccion', 'fecha_creacion')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B6168D16DE5')
    )
    # ### end Alembic commands ###
