"""se creo a asginaciondocentecurso el campo seccion 1

Revision ID: 6a274c91a991
Revises: 484e9d8c793e
Create Date: 2025-08-22 10:21:06.927846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a274c91a991'
down_revision: Union[str, None] = '484e9d8c793e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignacion_curso_docente', sa.Column('seccion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asignacion_curso_docente', 'seccion')
    # ### end Alembic commands ###
