"""se hizo nuleable el nombre seccion

Revision ID: 6e78d9da28c2
Revises: 2fe2234799a2
Create Date: 2025-08-25 09:26:43.597560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e78d9da28c2'
down_revision: Union[str, None] = '2fe2234799a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
