"""se agrego fecha inicio a asignacion

Revision ID: 7e6af1d9fd5c
Revises: 6123d788e8f2
Create Date: 2025-08-12 11:04:17.524835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6af1d9fd5c'
down_revision: Union[str, None] = '6123d788e8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones', sa.Column('fecha_inicio', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asignaciones', 'fecha_inicio')
    # ### end Alembic commands ###
