"""correccion en la tabla asignacion

Revision ID: 81836482a1e4
Revises: 4cf4631e1957
Create Date: 2025-08-26 09:47:50.074524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '81836482a1e4'
down_revision: Union[str, None] = '4cf4631e1957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.add_column('asignaciones', sa.Column('seccion_asignada', sa.Boolean(), nullable=True))
    op.drop_column('asignaciones', 'seccione_asignada')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones', sa.Column('seccione_asignada', mssql.BIT(), autoincrement=False, nullable=True))
    op.drop_column('asignaciones', 'seccion_asignada')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61340AE304')
    )
    # ### end Alembic commands ###
