"""Creación de tablas docentes, cursos, asignaciones

Revision ID: 85035f41f946
Revises: abc408921dbb
Create Date: 2025-08-20 18:19:11.424262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '85035f41f946'
down_revision: Union[str, None] = 'abc408921dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignacion_curso_docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignacion_curso_docente_id'), 'asignacion_curso_docente', ['id'], unique=False)
    op.drop_table('asignacion_docente')
    op.drop_table('asignacion_curso')
    op.drop_table('sysdiagrams')
    op.alter_column('asignaciones', 'plan',
               existing_type=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               nullable=False)
    op.alter_column('asignaciones', 'ciclo',
               existing_type=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asignaciones', 'ciclo',
               existing_type=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               nullable=True)
    op.alter_column('asignaciones', 'plan',
               existing_type=sa.VARCHAR(collation='Modern_Spanish_CI_AS'),
               nullable=True)
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B619B751772')
    )
    op.create_table('asignacion_curso',
    sa.Column('asignacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('curso_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], name='FK__asignacio__asign__18EBB532'),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], name='FK__asignacio__curso__19DFD96B'),
    sa.PrimaryKeyConstraint('asignacion_id', 'curso_id', name='PK__asignaci__3F9F2A7904EBBB52')
    )
    op.create_table('asignacion_docente',
    sa.Column('asignacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('docente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], name='FK__asignacio__asign__151B244E'),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], name='FK__asignacio__docen__160F4887'),
    sa.PrimaryKeyConstraint('asignacion_id', 'docente_id', name='PK__asignaci__39633D1AB4DEDE70')
    )
    op.drop_index(op.f('ix_asignacion_curso_docente_id'), table_name='asignacion_curso_docente')
    op.drop_table('asignacion_curso_docente')
    # ### end Alembic commands ###
