"""actualizo modelo HorarioAcademico1

Revision ID: 90cbc2ffcee7
Revises: 35acd5d5223a
Create Date: 2025-07-09 11:24:40.670189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90cbc2ffcee7'
down_revision: Union[str, None] = '35acd5d5223a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
