"""correccion tabla asignacion para nullear docente

Revision ID: 9a290bad9014
Revises: ac9cab2d7187
Create Date: 2025-07-25 15:05:57.221882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '9a290bad9014'
down_revision: Union[str, None] = 'ac9cab2d7187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carreraid', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('ciclo', sa.String(), nullable=True),
    sa.Column('cantidad_secciones', sa.Integer(), nullable=True),
    sa.Column('secciones_asignadas', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificada', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_id'), 'asignaciones', ['id'], unique=False)
    op.create_table('asignacion_docente',
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('asignacion_id', 'docente_id')
    )
    op.create_table('asignacion_curso',
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('asignacion_id', 'curso_id')
    )
    op.drop_table('asignacion_docente_curso')
    op.drop_index('ix_asignacion_id', table_name='asignacion')
    op.drop_table('asignacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignacion',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('carreraid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ciclo', sa.VARCHAR(length=10, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('cantidad_secciones', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('secciones_asignadas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_asignacion', mssql.DATETIMEOFFSET(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('fecha_modificada', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=True),
    sa.Column('estado', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('plan', sa.VARCHAR(length=10, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carreraid'], ['carrera.id'], name='FK__asignacio__carre__03F0984C'),
    sa.PrimaryKeyConstraint('id', name='PK__asignaci__3213E83FB44F91BE')
    )
    op.create_index('ix_asignacion_id', 'asignacion', ['id'], unique=False)
    op.create_table('asignacion_docente_curso',
    sa.Column('asignacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('docente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('curso_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignacion.id'], name='FK__asignacio__asign__0B91BA14'),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], name='FK__asignacio__curso__0C85DE4D'),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], name='FK__asignacio__docen__0D7A0286'),
    sa.PrimaryKeyConstraint('asignacion_id', 'docente_id', 'curso_id', name='PK__asignaci__183E46274DD6D936')
    )
    op.drop_table('asignacion_curso')
    op.drop_table('asignacion_docente')
    op.drop_index(op.f('ix_asignaciones_id'), table_name='asignaciones')
    op.drop_table('asignaciones')
    # ### end Alembic commands ###
