"""campo nulleable en horario

Revision ID: 9c4d31175c72
Revises: b3163734ebb8
Create Date: 2025-08-28 12:16:38.896570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4d31175c72'
down_revision: Union[str, None] = 'b3163734ebb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignacion_seccion',
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], ),
    sa.PrimaryKeyConstraint('asignacion_id', 'seccion_id')
    )
    op.alter_column('disponibilidad_docente', 'horarios',
               existing_type=sa.NVARCHAR(collation='Modern_Spanish_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disponibilidad_docente', 'horarios',
               existing_type=sa.NVARCHAR(collation='Modern_Spanish_CI_AS'),
               nullable=False)
    op.drop_table('asignacion_seccion')
    # ### end Alembic commands ###
