"""Actualizo los campos de usuario

Revision ID: a7aecbfb4861
Revises: 668b77d003d0
Create Date: 2025-08-28 15:47:49.776802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7aecbfb4861'
down_revision: Union[str, None] = '668b77d003d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
