"""modificacion tabla asignacion aumentar plan

Revision ID: ac9cab2d7187
Revises: ee6d798459e4
Create Date: 2025-07-25 14:54:32.534694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9cab2d7187'
down_revision: Union[str, None] = 'ee6d798459e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignacion', sa.Column('plan', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asignacion', 'plan')
    # ### end Alembic commands ###
