"""se modifico disponibilidad 1 

Revision ID: b3163734ebb8
Revises: 04d3fa28a0b5
Create Date: 2025-08-27 10:47:20.447916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3163734ebb8'
down_revision: Union[str, None] = '04d3fa28a0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
