"""se agrego activo a asignacion

Revision ID: b93cacf2756b
Revises: 46420988d340
Create Date: 2025-10-28 10:03:58.300767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93cacf2756b'
down_revision: Union[str, None] = '46420988d340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asignaciones', 'activo')
    # ### end Alembic commands ###
