"""inicial

Revision ID: c368405cec56
Revises: 
Create Date: 2025-07-07 17:50:37.187859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c368405cec56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('docente', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('tipoambiente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('colorhex', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiposevento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ambientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipoid', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('equipamiento', sa.String(length=255), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tipoid'], ['tipoambiente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('rolid', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fechacreacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rolid'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambienteid', sa.Integer(), nullable=True),
    sa.Column('cursoid', sa.Integer(), nullable=True),
    sa.Column('diasemana', sa.String(length=15), nullable=True),
    sa.Column('horainicio', sa.String(length=5), nullable=True),
    sa.Column('horafin', sa.String(length=5), nullable=True),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.Column('docente', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ambienteid'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['cursoid'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('ambiente_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('hora_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('aprobador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_evento_id'], ['tiposevento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aprobacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservaid', sa.Integer(), nullable=True),
    sa.Column('aprobadorid', sa.Integer(), nullable=True),
    sa.Column('tipoaprobador', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['reservaid'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacorareservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=True),
    sa.Column('realizadopor', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventosespeciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservaid', sa.Integer(), nullable=True),
    sa.Column('nombreevento', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('horainicio', sa.String(length=5), nullable=True),
    sa.Column('horafin', sa.String(length=5), nullable=True),
    sa.Column('organizador', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['reservaid'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventosespeciales')
    op.drop_table('bitacorareservas')
    op.drop_table('aprobacion')
    op.drop_table('reservas')
    op.drop_table('horarios')
    op.drop_table('usuarios')
    op.drop_table('ambientes')
    op.drop_table('tiposevento')
    op.drop_table('tipoambiente')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('cursos')
    # ### end Alembic commands ###
