"""agregando seccion

Revision ID: c690cf78c0a5
Revises: 9e22bc3c4ea3
Create Date: 2025-07-15 18:01:41.718056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c690cf78c0a5'
down_revision: Union[str, None] = '9e22bc3c4ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=True),
    sa.Column('carreraid', sa.Integer(), nullable=True),
    sa.Column('ciclo', sa.Integer(), nullable=True),
    sa.Column('letra', sa.String(length=1), nullable=True),
    sa.Column('turno', sa.String(length=1), nullable=True),
    sa.Column('serie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carreraid'], ['carrera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seccion_id'), 'seccion', ['id'], unique=False)
    op.drop_column('carrera', 'turno')
    op.add_column('cursos', sa.Column('carreid', sa.Integer(), nullable=True))
    op.drop_constraint('FK__cursos__carrerai__6C190EBB', 'cursos', type_='foreignkey')
    op.create_foreign_key(None, 'cursos', 'carrera', ['carreid'], ['id'])
    op.drop_column('cursos', 'carreraid')
    op.add_column('horarios', sa.Column('seccionid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'horarios', 'seccion', ['seccionid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'horarios', type_='foreignkey')
    op.drop_column('horarios', 'seccionid')
    op.add_column('cursos', sa.Column('carreraid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cursos', type_='foreignkey')
    op.create_foreign_key('FK__cursos__carrerai__6C190EBB', 'cursos', 'carrera', ['carreraid'], ['id'])
    op.drop_column('cursos', 'carreid')
    op.add_column('carrera', sa.Column('turno', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_seccion_id'), table_name='seccion')
    op.drop_table('seccion')
    # ### end Alembic commands ###
