"""actualización fecha usuario

Revision ID: cec154a8dc74
Revises: 55acdc6929fc
Create Date: 2025-07-08 18:38:58.221949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec154a8dc74'
down_revision: Union[str, None] = '55acdc6929fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('fechaactualizacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fechaactualizacion')
    # ### end Alembic commands ###
