"""agrega estado a la tabla carrera corregido

Revision ID: d3115f971a56
Revises: 2625a6401ee6
Create Date: 2025-07-21 18:15:43.007646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3115f971a56'
down_revision: Union[str, None] = '2625a6401ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrera', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrera', 'status')
    # ### end Alembic commands ###
