"""se agrego modalidad a curso

Revision ID: d4cf42aab129
Revises: 7e6af1d9fd5c
Create Date: 2025-08-15 15:40:15.360113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cf42aab129'
down_revision: Union[str, None] = '7e6af1d9fd5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('modalidad', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'modalidad')
    # ### end Alembic commands ###
