"""agrega estado a la tabla carrera corregido1

Revision ID: dd540581b3d0
Revises: d3115f971a56
Create Date: 2025-07-21 18:19:05.671264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'dd540581b3d0'
down_revision: Union[str, None] = 'd3115f971a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carrera', 'status',
               existing_type=mssql.BIT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carrera', 'status',
               existing_type=mssql.BIT(),
               nullable=True)
    # ### end Alembic commands ###
