"""Actualizo los campos de usuario1

Revision ID: ddbeba9c6e16
Revises: a7aecbfb4861
Create Date: 2025-08-28 15:51:54.114983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddbeba9c6e16'
down_revision: Union[str, None] = 'a7aecbfb4861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('calle_tipo', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('calle_nombre', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('calle_numero', sa.String(length=10), nullable=True))
    op.add_column('usuarios', sa.Column('ciudad', sa.String(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('departamento', sa.String(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('contacto_nombre', sa.String(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('contacto_numero', sa.String(length=20), nullable=True))
    op.drop_column('usuarios', 'direccion')
    op.drop_column('usuarios', 'contacto_emergencia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('contacto_emergencia', sa.VARCHAR(length=100, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('direccion', sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('usuarios', 'contacto_numero')
    op.drop_column('usuarios', 'contacto_nombre')
    op.drop_column('usuarios', 'departamento')
    op.drop_column('usuarios', 'ciudad')
    op.drop_column('usuarios', 'calle_numero')
    op.drop_column('usuarios', 'calle_nombre')
    op.drop_column('usuarios', 'calle_tipo')
    # ### end Alembic commands ###
