"""se hizo nuleable el nombre seccion1

Revision ID: e0e5c1c0c47c
Revises: 6e78d9da28c2
Create Date: 2025-08-25 09:27:00.577335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e5c1c0c47c'
down_revision: Union[str, None] = '6e78d9da28c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
