"""agrega plan a la tabla curso

Revision ID: f05da398bb8f
Revises: 676d1c9d82c9
Create Date: 2025-07-22 17:35:15.876269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05da398bb8f'
down_revision: Union[str, None] = '676d1c9d82c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('plan', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'plan')
    # ### end Alembic commands ###
