"""Modificacio nuleable a asignacion

Revision ID: f3c978661131
Revises: 3d91eec34b97
Create Date: 2025-07-25 12:25:09.945954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c978661131'
down_revision: Union[str, None] = '3d91eec34b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asignacion', 'horas_actuales',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asignacion', 'horas_actuales',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
