"""Actualizo los campos de usuario agrego campo coddocente

Revision ID: fa31141d2b59
Revises: ddbeba9c6e16
Create Date: 2025-10-22 13:10:11.749245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa31141d2b59'
down_revision: Union[str, None] = 'ddbeba9c6e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('cod_docente', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'cod_docente')
    # ### end Alembic commands ###
